[package]
name = "vts_yosys"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
vts-yosys-sys = { path = "./vts-yosys-sys" }

[dev-dependencies]
serial_test.workspace = true
