from enum import Enum
from typing import Mapping


class PyPortKind(Enum):
    INPUT = ...
    OUTPUT = ...


class PyPortClass(Enum):
    CLOCK = ...
    LUT_IN = ...
    LUT_OUT = ...
    LATCH_IN = ...
    LATCH_OUT = ...


class PyPort:
    def __init__(
        self,
        name: str,
        kind: PyPortKind,
        n_pins: int | None = None,
        class_: PyPortClass | None = None,
    ) -> None: ...


class PyComponentClass(Enum):
    LUT = ...
    LATCH = ...


class PyComponent:
    def __init__(self, name: str, class_: PyComponentClass | None = None) -> None: ...

    @property
    def name(self) -> str: ...

    @property
    def ports(self) -> dict[str, PyPort]: ...

    @property
    def children(self) -> dict[str, "PyComponent"]: ...

    @property
    def class_(self) -> PyComponentClass | None: ...

    def add_port(self, name: str, port: PyPort) -> None: ...

    def add_ports(self, ports: Mapping) -> None: ...
