[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "vts_api._vts_api_rs"

[tool.ruff.lint.isort]
combine-as-imports = true
