[package]
name = "vts_arch_py"
version = "0.0.0"
edition = "2021"

[dependencies]
vts_arch = { path = "../vts_arch" }
pyo3 = { version = "0.20.2", features = ["extension-module", "hashbrown"] }

[lib]
name = "vts_arch"
crate-type = ["cdylib"]
