on:
  push:
    branches:
      - main
    paths:
      - 'crates/vts_core/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/vts_core_ci.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Cargo check
        run: cargo check --package vts_core

      - name: Cargo build
        run: cargo build --verbose --package vts_core

      - name: Cargo test
        run: cargo test --verbose --package vts_core

      - name: Cargo clippy
        run: cargo clippy --package vts_core
